-- ResolveAI knowledge base: run this file in the Supabase SQL Editor before seeding.
create extension if not exists vector with schema extensions;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  content text not null,
  embedding extensions.vector(768) not null,
  created_at timestamptz not null default now()
);

create or replace function public.match_documents(
  query_embedding extensions.vector(768),
  match_threshold double precision,
  match_count integer
)
returns table (
  id bigint,
  title text,
  category text,
  content text,
  similarity double precision
)
language sql
stable
as $$
  select
    documents.id,
    documents.title,
    documents.category,
    documents.content,
    1 - (documents.embedding <=> query_embedding) as similarity
  from public.documents as documents
  where 1 - (documents.embedding <=> query_embedding) >= match_threshold
  order by documents.embedding <=> query_embedding
  limit match_count;
$$;
